theme ="solarized_light"

[editor]
line-number = "relative"
auto-pairs = false

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true

[editor.inline-diagnostics]
cursor-line = "error"
